const data = [
    {
        id:1,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:2,
        name:"range rover",
        carmodel:"classic",
        engine:"bs7",
    },
    {
        id:3,
        name:"range rover",
        carmodel:"premium",
        engine:"bs9",
    },
    {
        id:4,
        name:"BMW",
        carmodel:"x6",
        engine:"bs7",
    },
    {
        id:5,
        name:"BMW",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:6,
        name:"BMW",
        carmodel:"x9",
        engine:"bs9",
    },
    {
        id:7,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:8,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:9,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:10,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:11,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:12,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:13,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:14,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:15,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:16,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:17,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:18,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:19,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:20,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:21,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:22,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
    {
        id:24,
        name:"range rover",
        carmodel:"sportz",
        engine:"bs8",
    },
]

console.log(data)